// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: server.proto

package movies

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MoviesServer_GetNavigation_FullMethodName = "/server.MoviesServer/GetNavigation"
	MoviesServer_GetRecommend_FullMethodName  = "/server.MoviesServer/GetRecommend"
	MoviesServer_GetPlayLine_FullMethodName   = "/server.MoviesServer/GetPlayLine"
	MoviesServer_GetVideoList_FullMethodName  = "/server.MoviesServer/GetVideoList"
)

// MoviesServerClient is the client API for MoviesServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoviesServerClient interface {
	GetNavigation(ctx context.Context, in *GetNavigationRequest, opts ...grpc.CallOption) (*GetNavigationResponse, error)
	GetRecommend(ctx context.Context, in *GetRecommendRequest, opts ...grpc.CallOption) (*GetRecommendResponse, error)
	GetPlayLine(ctx context.Context, in *GetPlayLineRequest, opts ...grpc.CallOption) (*GetPlayLineResponse, error)
	GetVideoList(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error)
}

type moviesServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMoviesServerClient(cc grpc.ClientConnInterface) MoviesServerClient {
	return &moviesServerClient{cc}
}

func (c *moviesServerClient) GetNavigation(ctx context.Context, in *GetNavigationRequest, opts ...grpc.CallOption) (*GetNavigationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNavigationResponse)
	err := c.cc.Invoke(ctx, MoviesServer_GetNavigation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesServerClient) GetRecommend(ctx context.Context, in *GetRecommendRequest, opts ...grpc.CallOption) (*GetRecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendResponse)
	err := c.cc.Invoke(ctx, MoviesServer_GetRecommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesServerClient) GetPlayLine(ctx context.Context, in *GetPlayLineRequest, opts ...grpc.CallOption) (*GetPlayLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayLineResponse)
	err := c.cc.Invoke(ctx, MoviesServer_GetPlayLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesServerClient) GetVideoList(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoResponse)
	err := c.cc.Invoke(ctx, MoviesServer_GetVideoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoviesServerServer is the server API for MoviesServer service.
// All implementations must embed UnimplementedMoviesServerServer
// for forward compatibility
type MoviesServerServer interface {
	GetNavigation(context.Context, *GetNavigationRequest) (*GetNavigationResponse, error)
	GetRecommend(context.Context, *GetRecommendRequest) (*GetRecommendResponse, error)
	GetPlayLine(context.Context, *GetPlayLineRequest) (*GetPlayLineResponse, error)
	GetVideoList(context.Context, *GetVideoRequest) (*GetVideoResponse, error)
	mustEmbedUnimplementedMoviesServerServer()
}

// UnimplementedMoviesServerServer must be embedded to have forward compatible implementations.
type UnimplementedMoviesServerServer struct {
}

func (UnimplementedMoviesServerServer) GetNavigation(context.Context, *GetNavigationRequest) (*GetNavigationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNavigation not implemented")
}
func (UnimplementedMoviesServerServer) GetRecommend(context.Context, *GetRecommendRequest) (*GetRecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommend not implemented")
}
func (UnimplementedMoviesServerServer) GetPlayLine(context.Context, *GetPlayLineRequest) (*GetPlayLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayLine not implemented")
}
func (UnimplementedMoviesServerServer) GetVideoList(context.Context, *GetVideoRequest) (*GetVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoList not implemented")
}
func (UnimplementedMoviesServerServer) mustEmbedUnimplementedMoviesServerServer() {}

// UnsafeMoviesServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoviesServerServer will
// result in compilation errors.
type UnsafeMoviesServerServer interface {
	mustEmbedUnimplementedMoviesServerServer()
}

func RegisterMoviesServerServer(s grpc.ServiceRegistrar, srv MoviesServerServer) {
	s.RegisterService(&MoviesServer_ServiceDesc, srv)
}

func _MoviesServer_GetNavigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNavigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServerServer).GetNavigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoviesServer_GetNavigation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServerServer).GetNavigation(ctx, req.(*GetNavigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoviesServer_GetRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServerServer).GetRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoviesServer_GetRecommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServerServer).GetRecommend(ctx, req.(*GetRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoviesServer_GetPlayLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServerServer).GetPlayLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoviesServer_GetPlayLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServerServer).GetPlayLine(ctx, req.(*GetPlayLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoviesServer_GetVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServerServer).GetVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoviesServer_GetVideoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServerServer).GetVideoList(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoviesServer_ServiceDesc is the grpc.ServiceDesc for MoviesServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoviesServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.MoviesServer",
	HandlerType: (*MoviesServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNavigation",
			Handler:    _MoviesServer_GetNavigation_Handler,
		},
		{
			MethodName: "GetRecommend",
			Handler:    _MoviesServer_GetRecommend_Handler,
		},
		{
			MethodName: "GetPlayLine",
			Handler:    _MoviesServer_GetPlayLine_Handler,
		},
		{
			MethodName: "GetVideoList",
			Handler:    _MoviesServer_GetVideoList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
