// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: server.proto

package server

import (
	"context"

	"movies/rpc/internal/logic"
	"movies/rpc/internal/svc"
	"movies/rpc/movies"
)

type MoviesServerServer struct {
	svcCtx *svc.ServiceContext
	movies.UnimplementedMoviesServerServer
}

func NewMoviesServerServer(svcCtx *svc.ServiceContext) *MoviesServerServer {
	return &MoviesServerServer{
		svcCtx: svcCtx,
	}
}

func (s *MoviesServerServer) Ping(ctx context.Context, in *movies.Request) (*movies.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
