// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: server.proto

package moviesserver

import (
	"context"

	"movies_server/rpc/movies"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetNavigationRequest  = movies.GetNavigationRequest
	GetNavigationResponse = movies.GetNavigationResponse
	NavigationModel       = movies.NavigationModel

	MoviesServer interface {
		GetNavigation(ctx context.Context, in *GetNavigationRequest, opts ...grpc.CallOption) (*GetNavigationResponse, error)
	}

	defaultMoviesServer struct {
		cli zrpc.Client
	}
)

func NewMoviesServer(cli zrpc.Client) MoviesServer {
	return &defaultMoviesServer{
		cli: cli,
	}
}

func (m *defaultMoviesServer) GetNavigation(ctx context.Context, in *GetNavigationRequest, opts ...grpc.CallOption) (*GetNavigationResponse, error) {
	client := movies.NewMoviesServerClient(m.cli.Conn())
	return client.GetNavigation(ctx, in, opts...)
}
