// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: server.proto

package server

import (
	"context"

	"movies_server/rpc/internal/logic/moviesserver"
	"movies_server/rpc/internal/svc"
	"movies_server/rpc/movies"
)

type MoviesServerServer struct {
	svcCtx *svc.ServiceContext
	movies.UnimplementedMoviesServerServer
}

func NewMoviesServerServer(svcCtx *svc.ServiceContext) *MoviesServerServer {
	return &MoviesServerServer{
		svcCtx: svcCtx,
	}
}

func (s *MoviesServerServer) GetNavigation(ctx context.Context, in *movies.GetNavigationRequest) (*movies.GetNavigationResponse, error) {
	l := moviesserverlogic.NewGetNavigationLogic(ctx, s.svcCtx)
	return l.GetNavigation(in)
}
