// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: server.proto

package server

import (
	"context"
	"movies_server/common/movies"

	"movies_server/rpc/internal/logic/moviesserver"
	"movies_server/rpc/internal/svc"
)

type MoviesServerServer struct {
	svcCtx *svc.ServiceContext
	movies.UnimplementedMoviesServerServer
}

func NewMoviesServerServer(svcCtx *svc.ServiceContext) *MoviesServerServer {
	return &MoviesServerServer{
		svcCtx: svcCtx,
	}
}

func (s *MoviesServerServer) GetNavigation(ctx context.Context, in *movies.GetNavigationRequest) (*movies.GetNavigationResponse, error) {
	l := moviesserverlogic.NewGetNavigationLogic(ctx, s.svcCtx)
	return l.GetNavigation(in)
}

func (s *MoviesServerServer) GetRecommend(ctx context.Context, in *movies.GetRecommendRequest) (*movies.GetRecommendResponse, error) {
	l := moviesserverlogic.NewGetRecommendLogic(ctx, s.svcCtx)
	return l.GetRecommend(in)
}

func (s *MoviesServerServer) GetPlayLine(ctx context.Context, in *movies.GetPlayLineRequest) (*movies.GetPlayLineResponse, error) {
	l := moviesserverlogic.NewGetPlayLineLogic(ctx, s.svcCtx)
	return l.GetPlayLine(in)
}
