// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	home "movies_server/server/internal/handler/home"
	"movies_server/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/getNavigation",
				Handler: home.GetNavigationServerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getRecommend",
				Handler: home.GetRecommendServerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
